[project]
name = "lerobot-trial"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dora-rs-cli>=0.3.13",
    "fastapi>=0.122.0",
    "lerobot[aloha]>=0.4.2",
    "rerun-sdk[notebook]>=0.26.2",
    "types-requests>=2.32.4",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = [
    "ipyfilechooser>=0.6.0",
    "jupyter>=1.1.1",
    "maturin>=1.10.2",
    "mypy>=1.19.0",
    "nbstripout>=0.8.2",
    "pytest>=9.0.1",
    "ruff>=0.14.7",
    "rumdl>=0.0.185",
]

[build-system]
requires = ["maturin>=1.10.2,<2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "lerobot_trial._rust"
python-packages = ["lerobot_trial"]
python-source = "src"

[tool.uv]
cache-keys = [
  { file = "pyproject.toml" },
  { file = "rust/src/**/*.rs" },
  { file = "rust/Cargo.toml" },
  { file = "rust/Cargo.lock" },
]

[tool.uv.sources]
lerobot = { path = "lerobot", editable = true }

[project.scripts]
lerobot-trial = "lerobot_trial:main"

[tool.mypy]
exclude = ["lerobot"]
strict = true
ignore_missing_imports = true

[tool.pytest.ini_options]
norecursedirs = ["lerobot"]

[tool.ruff]
extend-exclude = ["lerobot"]

[tool.ruff.lint]
select = ["ALL"]  # ref. https://docs.astral.sh/ruff/rules/
ignore = [
  "A00",
  "COM",
  "D10",
  "D20",
  "D21",
  "E50",
  "EM1",
  "ERA",
  "FIX",
  "G00",
  "INP",
  "PLR",
  "S10",
  "T20",
  "TC0",
  "TD0",
  "TRY",
]
