def hello_from_bin() -> str: ...
def create_handlers(
    grpc_url: str | None = None,
    rrd_path: str | None = None,
    flush_tick_millis: int | None = None,
) -> tuple[DoraHandler, RerunClient]: ...

class DoraHandler:
    def try_recv(self) -> DoraInput | None: ...
    def is_running(self) -> bool: ...
    def send_action(self, data: list[float]) -> None: ...
    def send_reset(self) -> None: ...

class DoraInput:
    id: str
    array: object
    shape: list[int]

class RerunClient:
    def log_encoded_image(self, path: str, data: bytes) -> None: ...
    def start_recording(self) -> None: ...
    def stop_recording(self) -> None: ...
    def is_running(self) -> bool: ...
