def hello_from_bin() -> str: ...

class DoraHandler:
    def __init__(self) -> None: ...
    def try_recv(self) -> DoraInput | None: ...
    def is_running(self) -> bool: ...

class DoraInput:
    id: str
    array: object
    shape: list[int]

    def __init__(self) -> None: ...

class RerunRecorder:
    def __init__(self) -> None: ...
    def log_rgb_image(
        self, path: str, data: bytes, width: int, height: int
    ) -> None: ...
    def log_scalars(self, path: str, values: list[float]) -> None: ...
