"""Dora node using Rust-based binding implementation with HTTP control.

This node demonstrates how to use the Rust-implemented DoraHandler and RerunClient
that handles Dora event processing and Rerun logging.

## Architecture

- Agent position data: Received by Rust, logged to Rerun, passed to Python
- Image data: Read from MJPEG HTTP stream, buffered in memory
- Action data: Generated using LeRobot pretrained ACT policy model
- HTTP API: Start/stop control loop via HTTP endpoints

## Dora Channels

### Inputs

- agent_pos: Robot joint positions (received by Rust, forwarded to Python)
- tick: Timer signal to keep the node alive

### Outputs

- action: Action data generated by ACT policy model

## HTTP Endpoints

- POST /control/start: Start control loop
- POST /control/stop: Stop control loop
- POST /control/reset: Reset gym environment
"""

import logging
import threading
import time
from collections.abc import Callable

import cv2
import torch
import uvicorn
from lerobot.datasets.lerobot_dataset import LeRobotDatasetMetadata
from lerobot.policies.act.modeling_act import ACTPolicy
from lerobot.policies.factory import make_pre_post_processors
from lerobot.utils.utils import init_logging
from numpy.typing import NDArray
from pydantic import computed_field
from pydantic_settings import BaseSettings

from lerobot_trial._rust import DoraHandler, RerunClient, create_handlers
from lerobot_trial.control_state import ControlState
from lerobot_trial.http import control_api

NO_DATA_SLEEP_INTERVAL = 5e-3  # seconds

logger = logging.getLogger(__name__)


class Config(BaseSettings):
    """Application configuration loaded from environment variables."""

    python_log: str = "INFO"
    mjpeg_host: str = "localhost"
    mjpeg_port: int = 8080
    model_id: str = "lerobot/act_aloha_sim_insertion_human"
    dataset_id: str = "lerobot/aloha_sim_insertion_human"
    http_host: str = "0.0.0.0"
    http_port: int = 8000
    rerun_grpc_url: str | None = None
    rerun_rrd_path: str | None = None
    rerun_flush_tick_millis: int | None = None

    @computed_field  # type: ignore[prop-decorator]
    @property
    def python_log_level(self) -> str:
        return self.python_log.upper()

    @computed_field  # type: ignore[prop-decorator]
    @property
    def mjpeg_stream_url(self) -> str:
        return f"http://{self.mjpeg_host}:{self.mjpeg_port}/stream"


class ImageBuffer:
    """Thread-safe buffer for storing the latest image from MJPEG stream."""

    def __init__(self) -> None:
        self._image: NDArray | None = None
        self._lock = threading.Lock()

    def update(self, image: NDArray) -> None:
        with self._lock:
            self._image = image

    def get(self) -> NDArray | None:
        with self._lock:
            return self._image


def image_logger_thread(
    stream_url: str,
    rerun_recorder: RerunClient,
    dora_handler: DoraHandler,
    image_buffer: ImageBuffer,
    control_state: ControlState,
) -> None:
    """Thread for reading image data from MJPEG stream and logging to Rerun."""
    logger.info(f"Opening MJPEG stream: {stream_url}")

    cap = cv2.VideoCapture(stream_url)
    if not cap.isOpened():
        logger.error(f"Cannot open MJPEG stream {stream_url}")
        return

    try:
        while dora_handler.is_running():
            success, frame = cap.read()
            if not success:
                logger.warning("Failed to read frame from MJPEG stream")
                time.sleep(NO_DATA_SLEEP_INTERVAL)
                continue

            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            image_buffer.update(frame_rgb)

            if not control_state.is_running():
                continue

            success, jpeg_buffer = cv2.imencode(
                ".jpg", frame_rgb, [cv2.IMWRITE_JPEG_QUALITY, 75]
            )
            if success:
                rerun_recorder.log_encoded_image(
                    "mjpeg_stream/image", jpeg_buffer.tobytes()
                )
                logger.debug(
                    f"Logged JPEG compressed image: {frame_rgb.shape[1]}x{frame_rgb.shape[0]}"
                )
            else:
                logger.warning("Failed to encode frame as JPEG")

    except (cv2.error, OSError, ValueError) as e:
        logger.error(f"Error in image logger thread: {e}")
    finally:
        cap.release()
        logger.info("Image logger thread exiting")


def start_image_thread(
    config: Config,
    rerun_recorder: RerunClient,
    dora_handler: DoraHandler,
    image_buffer: ImageBuffer,
    control_state: ControlState,
) -> threading.Thread:
    """Start image logger thread and wait for first image."""
    image_thread = threading.Thread(
        target=image_logger_thread,
        args=(
            config.mjpeg_stream_url,
            rerun_recorder,
            dora_handler,
            image_buffer,
            control_state,
        ),
        daemon=True,
    )
    image_thread.start()

    logger.debug("Waiting for first image from MJPEG stream...")
    while (first_image := image_buffer.get()) is None:
        time.sleep(NO_DATA_SLEEP_INTERVAL)
    logger.info(f"First image received: {first_image.shape}")

    return image_thread


def start_http_server(
    config: Config,
    control_state: ControlState,
    rerun_recorder: RerunClient,
    dora_handler: DoraHandler,
) -> uvicorn.Server:
    """Start HTTP server in background thread and wait until ready."""
    app = control_api.create_app(control_state, rerun_recorder, dora_handler)
    uvicorn_config = uvicorn.Config(app, host=config.http_host, port=config.http_port)
    server = uvicorn.Server(config=uvicorn_config)

    server_thread = threading.Thread(target=server.run, daemon=True)
    server_thread.start()

    while not server.started:
        time.sleep(NO_DATA_SLEEP_INTERVAL)

    logger.info(f"HTTP server started on {config.http_host}:{config.http_port}")
    return server


def run_inference_loop(
    model: ACTPolicy,
    preprocess: Callable,
    postprocess: Callable,
    dora_handler: DoraHandler,
    image_buffer: ImageBuffer,
    control_state: ControlState,
) -> None:
    """Run main inference loop processing agent positions and generating actions."""
    counter = 0
    while dora_handler.try_recv() is not None:
        counter += 1
    logger.info(f"Flushed {counter} stale data, starting main loop")

    while dora_handler.is_running():
        if (agent_pos_data := dora_handler.try_recv()) is None:
            time.sleep(NO_DATA_SLEEP_INTERVAL)
            continue

        if not control_state.is_running():
            model.reset()
            continue

        agent_pos = agent_pos_data.array.to_numpy()
        state = torch.from_numpy(agent_pos.copy()).float().unsqueeze(0)

        if (latest_image := image_buffer.get()) is None:
            logger.warning("No image available in buffer, skipping inference step")
            continue

        image = torch.from_numpy(latest_image).permute(2, 0, 1).float() / 255.0
        image = image.unsqueeze(0)

        obs = {
            "observation.state": state,
            "observation.images.top": image,
        }

        obs_preprocessed = preprocess(obs)

        with torch.no_grad():
            action = model.select_action(obs_preprocessed)

        action = postprocess(action)

        action_list = action.squeeze(0).cpu().numpy().tolist()
        dora_handler.send_action(action_list)
        logger.debug(f"Sent action: {len(action_list)} values")


def main(config: Config) -> None:
    dora_handler, rerun_recorder = create_handlers(
        grpc_url=config.rerun_grpc_url,
        rrd_path=config.rerun_rrd_path,
        flush_tick_millis=config.rerun_flush_tick_millis,
    )
    logger.info("DoraHandler and RerunClient initialized successfully")

    logger.info(f"Loading model: {config.model_id}")
    model = ACTPolicy.from_pretrained(config.model_id)
    model.eval()

    logger.info(f"Loading dataset metadata: {config.dataset_id}")
    dataset_metadata = LeRobotDatasetMetadata(config.dataset_id, revision="v3.0")
    preprocess, postprocess = make_pre_post_processors(
        model.config, dataset_stats=dataset_metadata.stats
    )

    logger.info("Model and processors initialized successfully")

    control_state = ControlState()
    image_buffer = ImageBuffer()

    start_image_thread(
        config,
        rerun_recorder,
        dora_handler,
        image_buffer,
        control_state,
    )

    server = start_http_server(config, control_state, rerun_recorder, dora_handler)

    try:
        run_inference_loop(
            model,
            preprocess,
            postprocess,
            dora_handler,
            image_buffer,
            control_state,
        )
    finally:
        server.should_exit = True
        logger.info("Shutdown signal sent to HTTP server")


if __name__ == "__main__":
    config = Config()
    init_logging(console_level=config.python_log_level)
    main(config)
