"""Dora node using Rust-based binding implementation with HTTP control.

This node demonstrates how to use the Rust-implemented DoraHandler and RerunClient
that handles Dora event processing and Rerun logging.

## Architecture

- Agent position data: Received by Rust, logged to Rerun, passed to Python
- Image data: Read from MJPEG HTTP stream, buffered in memory
- Action data: Generated using LeRobot pretrained ACT policy model
- HTTP API: Start/stop control loop via HTTP endpoints

## Dora Channels

### Inputs

- agent_pos: Robot joint positions (received by Rust, forwarded to Python)
- tick: Timer signal to keep the node alive

### Outputs

- action: Action data generated by ACT policy model

## HTTP Endpoints

- POST /control/start: Start control loop
- POST /control/stop: Stop control loop
- POST /control/reset: Reset gym environment
"""

import contextlib
import logging
import os
import threading
import time
from collections.abc import Generator

import cv2
import torch
import uvicorn
from lerobot.datasets.lerobot_dataset import LeRobotDatasetMetadata
from lerobot.policies.act.modeling_act import ACTPolicy
from lerobot.policies.factory import make_pre_post_processors
from lerobot.utils.utils import init_logging
from numpy.typing import NDArray

from lerobot_trial._rust import DoraHandler, RerunClient, create_handlers
from lerobot_trial.control_state import ControlState
from lerobot_trial.http import app as http_app

NO_DATA_SLEEP_INTERVAL = 5e-3  # seconds

logger = logging.getLogger(__name__)


class ImageBuffer:
    """Thread-safe buffer for storing the latest image from MJPEG stream."""

    def __init__(self) -> None:
        self._image: NDArray | None = None
        self._cond = threading.Condition()

    def update(self, image: NDArray) -> None:
        with self._cond:
            self._image = image
            self._cond.notify_all()

    def get(self) -> NDArray:
        with self._cond:
            while self._image is None:
                self._cond.wait()
            return self._image


def get_python_log_level() -> str:
    return os.getenv("PYTHON_LOG", "INFO").upper()


def get_mjpeg_stream_url() -> str:
    host = os.getenv("MJPEG_HOST", "localhost")
    port = os.getenv("MJPEG_PORT", "8080")
    return f"http://{host}:{port}/stream"


def get_model_id() -> str:
    return os.getenv("MODEL_ID", "lerobot/act_aloha_sim_insertion_human")


def get_dataset_id() -> str:
    return os.getenv("DATASET_ID", "lerobot/aloha_sim_insertion_human")


def get_http_host() -> str:
    return os.getenv("HTTP_HOST", "0.0.0.0")


def get_http_port() -> int:
    return int(os.getenv("HTTP_PORT", "8000"))


def get_rerun_rrd_path() -> str | None:
    return os.getenv("RERUN_RRD_PATH")


class UvicornServer(uvicorn.Server):
    """Uvicorn server for running in background thread."""

    @contextlib.contextmanager
    def run_in_thread(self) -> Generator[None, None, None]:
        """Run server in background thread with context manager."""
        thread = threading.Thread(target=self.run, daemon=True)
        thread.start()
        try:
            while not self.started:
                time.sleep(1e-3)
            yield
        finally:
            logger.info("Shutting down HTTP server")
            self.should_exit = True
            thread.join(timeout=3.0)
            logger.info("HTTP server stopped")


def image_logger_thread(
    rerun_recorder: RerunClient,
    dora_handler: DoraHandler,
    image_buffer: ImageBuffer,
    control_state: ControlState,
) -> None:
    """Thread for reading image data from MJPEG stream and logging to Rerun."""
    logger.info("Starting image logger thread for MJPEG stream")

    stream_url = get_mjpeg_stream_url()
    logger.info(f"Opening MJPEG stream: {stream_url}")

    cap = cv2.VideoCapture(stream_url)
    if not cap.isOpened():
        logger.error(f"Cannot open MJPEG stream {stream_url}")
        return

    try:
        while dora_handler.is_running():
            success, frame = cap.read()
            if not success:
                logger.warning("Failed to read frame from MJPEG stream")
                time.sleep(NO_DATA_SLEEP_INTERVAL)
                continue

            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            height, width, _ = frame_rgb.shape

            image_buffer.update(frame_rgb)

            if not control_state.is_running():
                continue

            success, jpeg_buffer = cv2.imencode(
                ".jpg",
                cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2BGR),
                [cv2.IMWRITE_JPEG_QUALITY, 75],
            )
            if success:
                rerun_recorder.log_encoded_image(
                    "mjpeg_stream/image", jpeg_buffer.tobytes()
                )
                logger.debug(
                    f"Logged JPEG compressed image from MJPEG stream: {width}x{height}"
                )
            else:
                logger.warning("Failed to encode frame as JPEG")

    except (cv2.error, OSError, ValueError) as e:
        logger.error(f"Error in image logger thread: {e}")
    finally:
        cap.release()
        logger.info("Image logger thread exiting")


def main() -> None:
    rrd_path = get_rerun_rrd_path()
    dora_handler, rerun_recorder = create_handlers(rrd_path)
    logger.info("DoraHandler and RerunClient initialized successfully")

    model_id = get_model_id()
    logger.info(f"Loading model: {model_id}")
    model = ACTPolicy.from_pretrained(model_id)
    model.eval()

    dataset_id = get_dataset_id()
    logger.info(f"Loading dataset metadata: {dataset_id}")
    dataset_metadata = LeRobotDatasetMetadata(dataset_id, revision="v3.0")
    preprocess, postprocess = make_pre_post_processors(
        model.config, dataset_stats=dataset_metadata.stats
    )

    logger.info("Model and processors initialized successfully")

    control_state = ControlState()
    image_buffer = ImageBuffer()

    # Create HTTP app with dependencies
    app = http_app.create_app(control_state, rerun_recorder, dora_handler)

    host, port = get_http_host(), get_http_port()
    config = uvicorn.Config(app, host=host, port=port)
    server = UvicornServer(config=config)

    with server.run_in_thread():
        logger.info(f"HTTP server started on {host}:{port}")

        image_thread = threading.Thread(
            target=image_logger_thread,
            args=(rerun_recorder, dora_handler, image_buffer, control_state),
            daemon=True,
        )
        image_thread.start()

        logger.info("Waiting for first image from MJPEG stream...")
        first_image = image_buffer.get()
        logger.info(f"First image received: {first_image.shape}")

        while dora_handler.try_recv() is not None:
            pass
        logger.info("Flushed stale data, starting main loop")

        while dora_handler.is_running():
            if (agent_pos_data := dora_handler.try_recv()) is None:
                time.sleep(NO_DATA_SLEEP_INTERVAL)
                continue

            if not control_state.is_running():
                model.reset()
                continue

            agent_pos = agent_pos_data.array.to_numpy()
            state = torch.from_numpy(agent_pos.copy()).float().unsqueeze(0)

            latest_image = image_buffer.get()
            image = torch.from_numpy(latest_image).permute(2, 0, 1).float() / 255.0
            image = image.unsqueeze(0)

            obs = {
                "observation.state": state,
                "observation.images.top": image,
            }

            obs_preprocessed = preprocess(obs)

            with torch.no_grad():
                action = model.select_action(obs_preprocessed)

            action = postprocess(action)

            action_list = action.squeeze(0).cpu().numpy().tolist()
            dora_handler.send_action(action_list)
            logger.debug(f"Sent action: {len(action_list)} values")

        image_thread.join(timeout=5.0)


if __name__ == "__main__":
    init_logging(console_level=get_python_log_level())
    main()
